# DigitalOcean App Platform Specification
# Upload this file when creating your app on DigitalOcean

name: premierprime-cleaning-app
region: nyc

services:
  # Backend API Service
  - name: backend
    source_dir: /backend
    github:
      repo: yourusername/premierprime-cleaning-app
      branch: main
    run_command: ./main
    build_command: go build -o main cmd/main.go
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    health_check:
      http_path: /api/health
    envs:
      - key: PORT
        value: "8080"
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-change-this-32-chars-min
        type: SECRET
      - key: GIN_MODE
        value: release
      - key: DB_HOST
        value: ${db.HOSTNAME}
      - key: DB_PORT
        value: ${db.PORT}
      - key: DB_USER
        value: ${db.USERNAME}
      - key: DB_PASSWORD
        value: ${db.PASSWORD}
      - key: DB_NAME
        value: ${db.DATABASE}
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}

  # Frontend Static Site
  - name: frontend
    source_dir: /frontend
    github:
      repo: yourusername/premierprime-cleaning-app
      branch: main
    build_command: npm run build
    output_dir: build
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    static_sites:
      - name: frontend
        output_dir: build
        index_document: index.html
        error_document: index.html

# PostgreSQL Database
databases:
  - name: db
    engine: PG
    version: "15"
    size: basic-xs
    num_nodes: 1